name: Flutter Web Deployment

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Setup Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x.x' # Gunakan versi stabil terbaru

      # 2. Get dependencies
      - run: flutter pub get

      # 3. Build the web app
      - run: flutter build web --release

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
